classdef uimovielabels < TComponent
    properties (Constant)
        Type        = 'Axes'
    end
    
    
    methods (Access = protected)
        function initialise(~)
        end
    end
    
    methods
        function obj = uimovielabels()
            obj.Width = 20;

            set(obj.Handle, ...
                ... Ticks
                'XTick', [], ...
                'YTick', [], ...
                ... Rulers
                'XLim', [0.5 1.5], ...
                'YLim', [0.5 1.5], ...
                'YDir', 'reverse', ...
                ... Colour
                'Color', 'w')
            text(obj.Handle, ...
                1, 1, 'Animation', ...
                ... Text
                'Color', 'k', ...
                ... Font
                'FontSize', 10, ...
                'FontName', 'FixedWidth', ...
                'FontWeight', 'bold', ...
                ... Text Box
                'Rotation', 90, ...
                ... Position
                'HorizontalAlignment', 'center', ...
                ... Callbacks
                'PickableParts', 'none')
        end
    end
end