classdef uiwavenumbersmain_text_select_multi < TComponent
    properties (Constant)
        Type = "hggroup"
    end
    properties (SetAccess = private)
        tx              (1,:)   matlab.graphics.Graphics = gobjects(0)
    end
    methods
        function updateuiview(obj)
           switch obj.Data.uiview.viewname
               case 'maps'
                   set(obj.Handle, ...
                       'Visible', 'on')
               otherwise
                   set(obj.Handle, ...
                       'Visible', 'off')
           end
        end
        function updateuimaps(obj)
            m = obj.Data.wave.medians;
            s = obj.Data.uimaps.selection;
            n = length(s);

            set(obj.tx(1:n), ...
                {'Position'}, num2cell([m(s)' zeros(n, 1)], 2), ...
                {'String'}, cellstr(string(s')), ... 
                'BackgroundColor', [128 128 128 128]/256, ...
                'Visible', 'on')
            set(obj.tx(n + 1:end), ...
                'Visible', 'off')
        end
    end
    methods
        function obj = uiwavenumbersmain_text_select_multi()
            set(obj.Handle, ...
                ... Callback Execution Control
                'PickableParts', 'none')

            obj.tx = text(obj.Handle, ...
                zeros(1, obj.Data.uimaps.n_max), ...
                zeros(1, obj.Data.uimaps.n_max), ...
                '', ...
                ... Text
                'Color', [032 032 032]/256, ...
                ... Font
                'FontSize', 8, ...
                'FontName', 'FixedWidth', ...
                'FontWeight', 'bold', ...
                ... Position
                'HorizontalAlignment', 'center', ...
                ... Callback Execution Control
                'HitTest', 'off');
        end
    end
end