classdef Scrollbar < matlab.mixin.SetGet 
    properties (Access = private)
        Axes
        Line
        Thumb
    end
    properties
        Direction       (1,:) char {mustBeMember(Direction,{'Vertical','Horizontal'})} = 'Vertical'
        
        Limits          (1,2) double = [0 1]
        ThumbPosition   (1,2) double = [0 1]
        ThumbColor      (1,3) double {...
            mustBeGreaterThanOrEqual(ThumbColor,0), ...
            mustBeLessThanOrEqual(ThumbColor,1)} = [0.5 0.5 0.5]
    end
    
    methods
        function obj = Scrollbar(parent)
            obj.Axes = axes(parent, ...
                ... Rulers
                'XLim', [0 1], ...
                'YLim', [0 1], ...
                'YDir', 'reverse', ...
                ... Position
                'PositionConstraint', 'innerposition', ...
                'Units', 'normalized', ...
                'Position', [0 0 1 1], ...
                ... Interactivity
                'NextPlot', 'add', ...
                'PickableParts', 'none', ...
                'Visible', 'off');
            obj.Line = xline(obj.Axes, 0.5, ...
                'Color', obj.ThumbColor, ...
                'PickableParts', 'none');
            obj.Thumb = line(obj.Axes, ...
                'XData', [0.5 0.5], ...
                'YData', [0.5 0.5], ...
                'Color', obj.ThumbColor, ...
                'LineWidth', 2, ...
                'PickableParts', 'none');
            
            obj.redraw()
        end
        
        function redraw(obj)
            switch obj.Direction
                case 'Vertical'
                    set(obj.Axes, ...
                        'XLim', [0 1], ...
                        'YLim', obj.Limits)
                    set(obj.Line, ...
                        'InterceptAxis', 'x', ...
                        'Color', obj.ThumbColor)
                    set(obj.Thumb, ...
                        'XData', [0.5 0.5], ...
                        'YData', obj.ThumbPosition, ...
                        'Color', obj.ThumbColor)
                case 'Horizontal'
                    set(obj.Axes, ...
                        'XLim', obj.Limits, ...
                        'YLim', [0 1])
                    set(obj.Line, ...
                        'InterceptAxis', 'y', ...
                        'Color', obj.ThumbColor)
                    set(obj.Thumb, ...
                        'XData', obj.ThumbPosition, ...
                        'YData', [0.5 0.5], ...
                        'Color', obj.ThumbColor)
            end
            if obj.ThumbPosition(1) > obj.Limits(1) || ...
                    obj.ThumbPosition(2) < obj.Limits(2)
                set(obj.Thumb, 'Visible', 'on')
            else
                set(obj.Thumb, 'Visible', 'off')
            end
        end
        
        function set.Direction(obj, dir)
            obj.Direction = dir;
            obj.redraw()
        end
        function set.Limits(obj, r)
            if range(r) > 0 && r(2) > r(1)
                obj.Limits = r;
            else
                obj.Limits = [0 1];
            end            
            obj.redraw()
        end
        function set.ThumbPosition(obj, r)
            if range(r) > 0 && r(2) > r(1)
                obj.ThumbPosition = r;
            else
                obj.ThumbPosition = [0 1];
            end            
            obj.redraw()
        end
        function set.ThumbColor(obj, c)
            obj.ThumbColor = c;
            obj.redraw()
        end
    end
end

