classdef uisignalmain_timestamps < TComponent
    properties (Constant)
        Type = 'hggroup'
    end
    methods
        function obj = uisignalmain_timestamps()
            t = 0:60:(60 * 60 * 2);
            [~, m, s] = hms(duration(0, 0, t));
            str = strcat( ...
                num2str(m', '%02.0f'), ...
                {':'}, ...
                num2str(s', '%02.0f'));
            
            text(obj.Handle, ...
                t, ...
                repmat(0.5, 1, length(t)), ...
                str, ...
                ... Text
                'Color', [0.25 0.25 0.25], ...
                'Interpreter', 'none', ...
                ... Font
                'FontName', 'FixedWidth', ...
                'FontSize', 8, ...
                ... Position
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'bottom');
        end
    end
end