classdef uieventviewerlabels < TComponent
    properties (Constant)
        Type = 'panel'
    end
    properties (SetAccess = immutable)
        ax; tx_i; tx_j
    end

    methods
        function updatecnfg(obj)
            nr = obj.Data.cnfg.size(1);
            nc = obj.Data.cnfg.size(2);

            set(obj.ax, ...
                'YLim', [-nr nc] + [-1 1])
            set(obj.tx_i, ...
                'Position', [1 -((nr/2) + 1)])
            set(obj.tx_j, ...
                'Position', [1 +((nc/2) + 1)])
        end
    end
    methods % CONSTRUCTOR
        function obj = uieventviewerlabels()
            obj.ax = axes(obj.Handle, ...
                ... Ticks
                'XTick', [], ...
                'YTick', 0, ...
                'TickLength', [0 0], ...
                ... Rulers
                'XLim', [0 1] + 0.5, ...
                'YLim', [-1 1], ...
                'YDir', 'reverse', ...
                'XColor', 'none', ...
                'YColor', 'none', ...
                ... Grids
                'YGrid', 'on', ...
                'GridColor', [0.15 0.15 0.15], ...
                ... Colour
                'Color', [1 1 1], ...
                ... Position
                'InnerPosition', [0 0 1 1]);
            obj.tx_i = text(obj.ax, ...
                1, -0.5, 'i', ...
                ... Text
                'Color', [0.5 0.5 0.5], ...
                ... Font
                'FontSize', 10, ...
                'FontName', 'FixedWidth', ...
                'FontWeight', 'bold', ...
                ... Text Box
                'Rotation', 90, ...
                ... Position
                'HorizontalAlignment', 'center');
            obj.tx_j = text(obj.ax, ...
                1, 0.5, 'j', ...
                ... Text
                'Color', [0.5 0.5 0.5], ...
                ... Font
                'FontSize', 10, ...
                'FontName', 'FixedWidth', ...
                'FontWeight', 'bold', ...
                ... Text Box
                'Rotation', 90, ...
                ... Position
                'HorizontalAlignment', 'center');
        end
    end     % CONSTRUCTOR
    methods (Access = protected)
        function initialise(obj)
            obj.Width = 20;
        end
    end     % PROTECTED
end