classdef uimoviepanel_time < TComponent
    properties (Constant)
        Type = 'Panel'
    end
    properties (Access = private)
        tx_current
        tx_duration
    end
    
    methods
        function updateuiflmv(obj)
            [h, m, s] = hms(duration(0, 0, obj.Data.uiflmv.cursor));
            str_time = [...
                num2str(h, '%02i') ':' ...
                num2str(m, '%02i') ':' ...
                num2str(round(s), '%02i')];
            set(obj.tx_current, 'String', str_time)

            [h, m, s] = hms(duration(0, 0, obj.Data.prop.duration));
            str_time = [...
                num2str(h, '%02i') ':' ...
                num2str(m, '%02i') ':' ...
                num2str(round(s), '%02i')];
            set(obj.tx_duration, 'String', str_time)    
        end
    end
    methods
        function obj = uimoviepanel_time()
            obj.Height = 45;

            set(obj.Handle, ...
                'Title', 'Playback Time', ...
                'BorderType', 'etchedin', ...
                'Padding', 5);
            
            h = uix.HBox( ...
                'Parent', obj.Handle, ...
                'BackgroundColor', obj.Handle.BackgroundColor);
            
            obj.tx_current = uicontrol(h, ...
                'Style', 'Text', ...
                'String', '00:00:00', ...
                'HorizontalAlignment', 'right', ...
                'BackgroundColor', obj.Handle.BackgroundColor);
            uicontrol(h, ...
                'Style', 'Text', ...
                'String', '/', ...
                'HorizontalAlignment', 'center', ...
                'BackgroundColor', obj.Handle.BackgroundColor)
            obj.tx_duration = uicontrol(h, ...
                'Style', 'Text', ...
                'String', '00:00:00', ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', obj.Handle.BackgroundColor);
            
            set(h, 'Widths', [-1 20 -1])
        end
    end
end

