classdef uiconfig_axes_flat < TComponent
    properties (Constant)
        Type = "axes"
    end
    properties (SetAccess = immutable)
        ln_b; ln_e; hg_t
        cm
    end

    methods
        function updatecnfg(obj)
            switch obj.Data.cnfg.mode
                case 'flat'
                    cf = obj.Data.cnfg.configuration;
                    sz = obj.Data.cnfg.size;

                    if ~all(sz);   return;   end

                    tf = cf > 0;
                    
                    x = obj.Data.cnfg.x;    
                    y = obj.Data.cnfg.y;    
                    
                    xg = NaN(sz);   xg(tf) = x(cf(tf));
                    yg = NaN(sz);   yg(tf) = y(cf(tf));

                    xg = padarray(xg, [1 1], NaN, 'post');
                    yg = padarray(yg, [1 1], NaN, 'post');

                    cf = padarray(cf, [1 1], NaN, 'post');
                    tf = padarray(tf, [1 1], false, 'post');
                    
                    set(obj.ln_b, ...
                        'XData', [reshape(xg, 1, []), reshape(xg', 1, [])], ...
                        'YData', [reshape(yg, 1, []), reshape(yg', 1, [])])
                    set(obj.ln_e, ...
                        'XData', x, ...
                        'YData', y)
                    delete(allchild(obj.hg_t))
                    text(obj.hg_t, ...
                        xg(tf), yg(tf), ...
                        cellstr(string(cf(tf))), ...
                        ... Text
                        'Color', 'k', ...
                        ... Font
                        'FontSize', 6, ...
                        'FontName', 'fixedwidth', ...
                        'FontWeight', 'bold', ...
                        ... Text Box
                        'BackgroundColor', 'none', ...
                        ... Position
                        'HorizontalAlignment', 'center', ...
                        'VerticalAlignment', 'middle', ...
                        ... Callback Execution Control
                        'PickableParts', 'none')
                    
                    xlim = [min(x) max(x)] + 0.1 * range(x, 'all') * [-1 1];
                    ylim = [min(y) max(y)] + 0.1 * range(y, 'all') * [-1 1];

                    set(obj.Handle, ...
                        'XLim', xlim, ...
                        'YLim', ylim)
                    
                    set(allchild(obj.Handle), ...
                        'Visible', 'on')
                case 'sphere'
                    set(allchild(obj.Handle), ...
                        'Visible', 'off')
            end
        end
    end
    methods (Access = protected)
        function mouseClickRight(obj)
            set(obj.cm, 'Visible', 'on', ...
                'Position', get(obj.Window, 'CurrentPoint'))
        end
        function menuFcn(obj, e)
            switch e.Source.Text
                case 'Load Configuration...'
                    obj.Data.cnfg.load()
            end
        end
    end
    methods % CONSTRUCTOR
        function obj = uiconfig_axes_flat()
            set(obj.Handle, ...
                ... Rulers
                'XLim', [0 1], ...
                'YLim', [0 1], ...
                'XColor', [172 172 172]/256, ...
                'YColor', [172 172 172]/256, ...
                'YDir', 'reverse', ...
                ... Box Styling
                'Box', 'on', ...
                ... Position
                'Units', 'normalized', ...
                'Position', [0.01 0.01 0.98 0.98], ...
                'DataAspectRatio', [1 1 1])

            % Plot components
            obj.ln_b = line(obj.Handle, ...
                ... Line
                'Color', [224 224 224]/256, ...
                'AlignVertexCenters', 'on', ...
                ... Data
                'XData', double.empty(1,0), ...
                'YData', double.empty(1,0), ...
                ... Callback Execution Control
                'PickableParts', 'none');
            obj.ln_e = line(obj.Handle, ...
                ... Line
                'LineStyle', 'none', ...
                ... Markers
                'Marker', 'o', ...
                'MarkerSize' , 8, ...
                'MarkerEdgeColor', 'none', ...
                'MarkerFaceColor', [224 224 224]/256, ...
                ... Data
                'XData', double.empty(1,0), ...
                'YData', double.empty(1,0), ...
                ... Callback Execution Control
                'PickableParts', 'none');
            obj.hg_t = hggroup(obj.Handle, ...
                ... Callback Execution Control
                'PickableParts', 'none');

            % Context menus
            obj.cm = uicontextmenu(obj.Window);
            uimenu(obj.cm, ...
                'Text', 'Load Configuration...')

            obj.addlistener(findobj(obj.cm, 'Children', gobjects(0)), ...
                'Action', @(~, e)obj.menuFcn(e))
        end
    end     % CONSTRUCTOR
end
