classdef uitimeline_highlight < TComponent
    properties (Constant)
        Type = "hggroup"
    end
    properties (SetAccess = immutable)
        ln_cursor
        ln_highlight
    end
    methods 
        function updateuiprvw_timeline(obj)
            w = obj.Data.uiprvw_timeline.width;
            
            t = obj.Data.uiprvw_timeline.t;
            i = obj.Data.uiprvw_timeline.i;

            if isnan(t) && isnan(i)
                set(obj.Handle, ...
                    'Visible', 'off')
            elseif ~isnan(t) && t
                x = rem(t, w);
                y = ceil(t/w);

                set(obj.ln_cursor, ...
                    'XData', [x x], ...
                    'YData', [y y] + [-0.5 0.5], ...
                    'Visible', 'on')
                set(obj.ln_highlight, ...
                    'Visible', 'off')
                set(obj.Handle, ...
                    'Visible', 'on')
            elseif ~isnan(i) && i
                t = obj.Data.wave.medians(i);
                
                x = rem(t, w);
                y = ceil(t/w);

                set(obj.ln_highlight, ...
                    'XData', x, ...
                    'YData', y, ...
                    'MarkerFaceColor', 'k', ...
                    'MarkerSize', 5, ...
                    'Visible', 'on')
                set(obj.ln_cursor, ...
                    'Visible', 'off')
                set(obj.Handle, ...
                    'Visible', 'on')
            end
        end
    end
    methods % CONSTRUCTOR
        function obj = uitimeline_highlight()
            set(obj.Handle, ...
                'PickableParts', 'none')

            obj.ln_cursor = line(obj.Handle, ...
                ... Line
                'Color', [128 128 128]/256, ...
                'AlignVertexCenters', 'on', ...
                ... Data
                'XData', [], ...
                'YData', []);
            obj.ln_highlight = line(obj.Handle, ...
                ... Data
                'XData', [], ...
                'YData', [], ...
                ... Marker
                'Marker', 'o', ...
                'MarkerSize', 5, ...
                'MarkerFaceColor', [000 000 000]/256, ...
                'MarkerEdgeColor', 'none');
        end
    end     % CONSTRUCTOR
end