classdef uiselect_line < TComponent
    properties (Constant)
        Type = 'line'
    end

    methods
        function updatecnfg(obj)
            set(obj.Handle, ...
                'XData', obj.Data.cnfg.x, ...
                'YData', obj.Data.cnfg.y)
        end
    end
    
    methods % CONSTRUCTOR
        function obj = uiselect_line()
            set(obj.Handle, ...
                ... Line
                'LineStyle', 'none', ...
                'LineWidth', 1, ...
                ... Marker
                'Marker', 'o', ...
                'MarkerSize', 12, ...
                'MarkerFaceColor', [0.9 0.9 1.0], ...
                'MarkerEdgeColor', [0.7 0.7 1.0], ...
                ... Data
                'XData', [], ...
                'YData', [])
        end
    end     % CONSTRUCTOR
end