classdef uiproperties_hide < TComponent
    properties (Constant)
        Type = "uipanel"
    end
    properties (SetAccess = immutable)
        ax
    end
    
    methods
        function updateuiview(obj)
            if obj.Data.uiview.property
                set(obj.ax, ...
                    'XDir', 'reverse')
            else
                set(obj.ax, ...
                    'XDir', 'normal')
            end
        end
    end
    methods (Access = protected)
        function mouseClick(obj)
            obj.Data.uiview.toggleVisibilityProperty()
        end

        function enterFcn(obj)
            set(obj.Window, ...
                'Pointer', 'hand')
            set(obj.Handle, ...
                'BackgroundColor', [232 232 232]/256)
        end
        function exitFcn(obj)
            set(obj.Window, ...
                'Pointer', 'arrow')
            set(obj.Handle, ...
                'BackgroundColor', [240 240 240]/256)
        end
    end
    methods
        function obj = uiproperties_hide()            
            obj.ax = axes(obj.Handle, ...
                ... Ticks
                'XTick', [], ...
                'YTick', [], ...
                'XTickMode', 'manual', ...
                'YTickMode', 'manual', ...
                'TickLength', [0 0], ...
                ... Rulers
                'XLim', [0 4], ...
                'YLim', [-50 50], ...
                'XLimMode', 'manual', ...
                'YLimMode', 'manual', ...
                'XColor', 'none', ...
                'YColor', 'none', ...
                'XDir', 'reverse', ...
                ... Multiple Plots
                'NextPlot', 'add', ...
                ... Box Styling
                'Color', [1 1 1], ...
                ... Position
                'Position', [0 0 1 1], ...
                'ActivePositionProperty', 'position', ...
                'DataAspectRatio', [1 1 1], ...
                ... Interactivity
                'Visible', 'off', ...
                ... Callback
                'PickableParts', 'none');

            drawObjects(obj.ax)
        end
    end
    methods (Access = protected)
        function initialise(obj)
            obj.Width = 7;
        end
    end
end

function drawObjects(h)
xt = [03.0 03.0 01.0 03.0];
yt = [45 41 43 45];

xt = [xt' xt'];
yt = [yt' yt'] .* [1 -1];

patch(h, ...
    ... Color
    'FaceColor', [0.8 0.8 0.8], ...
    'EdgeColor', 'none', ...
    ... Data
    'XData', xt, ...
    'YData', yt, ...
    ... Callback
    'PickableParts', 'none');

line(h, ...
    ... Color
    'LineStyle', 'none', ...
    ... Marker
    'Marker', 'o', ...
    'MarkerSize', 1.5, ...
    'MarkerEdgeColor', 'none', ...
    'MarkerFaceColor', [0.8 0.8 0.8], ...
    ... Data
    'XData', ones(size(-38:4:38)) * 2, ...
    'YData', -38:4:38, ...
    ... Callback
    'PickableParts', 'none');
end