classdef uimoviemain_axes < TComponent
    properties (Constant)
        Type = 'axes'
    end
    
    methods
        function updatecnfg(obj)
            sz = obj.Data.cnfg.size;
            if all(sz)
                set(obj.Handle, ...
                    'XLim', [0 sz(2) + 1], ...
                    'YLim', [0 sz(1) + 1])
            else
                set(obj.Handle, ...
                    'XLim', [0 1] + 0.5, ...
                    'YLim', [0 1] + 0.5)
            end
        end
    end
    methods (Access = protected)
        function initialise(~)
            uimoviemain_image();
        end
    end
    methods % CONSTRUCTOR
        function obj = uimoviemain_axes()
            set(obj.Handle, ...
                ... Ticks
                'XTick', [], ...
                'YTick', [], ...
                ... Rulers
                'XLim', [0.5 1.5], ...
                'YLim', [0.5 1.5], ...
                'YDir', 'reverse', ...
                ... Grids
                'YGrid', 'on', ...
                'GridColor', [0.15 0.15 0.15], ...
                ... Color
                'Colormap', gray, ...
                'CLimMode', 'manual', ...
                'CLim', [0 1], ...
                ... Box Styling
                'Color', 'k', ...
                ... Position
                'DataAspectRatioMode', 'manual', ...
                'DataAspectRatio', [1 1 1])
        end
    end     % CONSTRUCTOR
end