classdef uimaps_propagation_axes_sphere < TComponent
    properties (Constant)
        Type = 'axes'
    end
    properties (SetAccess = immutable)
        index
    end
    properties (SetAccess = immutable)
        sf_bg
        pa
    end
    properties (Access = private)
        clicked
    end

    methods
        function updatecnfg(obj)
            switch obj.Data.cnfg.mode
                case 'flat'
                    set(obj.sf_bg, ...
                        'Visible', 'off')
                    set(obj.pa, ...
                        'Visible', 'off')
                    set(obj.Handle, ...
                        'Visible', 'off', ...
                        'PickableParts', 'none')
                case 'sphere'
                    [x, y, z] = sph2cart( ...
                        obj.Data.cnfg.xg, ...
                        obj.Data.cnfg.yg, ...
                        0.98);
                    set(obj.sf_bg, ...
                        'XData', x, ...
                        'YData', y, ...
                        'ZData', z, ...
                        'EdgeColor', [128 128 128]/256, ...
                        'Visible', 'on')
                    set(obj.pa, ...
                        'Visible', 'on')
                    set(obj.Handle, ...
                        'Visible', 'off', ...
                        'PickableParts', 'all')
            end
        end
        function updateuimaps(obj)
            if strcmp('sphere', obj.Data.cnfg.mode) && ...
                    (obj.index <= obj.Data.uimaps.n)
                
                ig = obj.Data.uimaps.selection(obj.index);
                at = obj.Data.wave.waves(:, :, ig);

                in = obj.Data.uimaps.interval;

                lv = [min(at(:)) max(at(:))]/in;
                lv = in * (floor(lv(1)):ceil(lv(2)));

                [vx, vy, vz, cd] = obj.Data.a_cont.createContoursSphere(at, lv);

                set(obj.pa, ...
                    'XData', vx, ...
                    'YData', vy, ...
                    'ZData', vz, ...
                    'CData', cd)
                set(obj.Handle, ...
                    'Colormap', autumn(length(lv) - 1))
            end
        end
        function updateuimaps_view(obj)
            set(obj.Handle, ...
                'View', obj.Data.uimaps_view.view)
        end
    end
    methods (Access = protected)
        function initialise(obj)
        end
        function mouseClickLeft(obj)
            obj.clicked = get(0, 'PointerLocation');

            %e = obj.ClickedEvent
        end
        function mouseDrag(obj)
            p = get(0, 'PointerLocation');
            v = obj.Data.uimaps_view.view;

            obj.Data.uimaps_view.setView(v + obj.clicked - p)

            obj.clicked = p;
        end
    end
    methods % CONSTRUCTOR
        function obj = uimaps_propagation_axes_sphere()
            set(obj.Handle, ...
                ... Rulers
                'XLim', [-1 1], ...
                'YLim', [-1 1], ...
                'ZLim', [-1 1], ...
                'XColor', [192 192 192]/256, ...
                'YColor', [192 192 192]/256, ...
                'YDir', 'reverse', ...
                ... Box Styling
                'Color', 'w', ...
                'Box', 'on', ...
                ... Position
                'Units', 'normalized', ...
                'InnerPosition', [0.01 0.01 0.98 0.98], ...
                'DataAspectRatio', [1 1 1], ...
                ... View
                'View', [60 30], ...
                'CameraViewAngle', 10)

            obj.sf_bg = surf([], ...
                'Parent', obj.Handle, ...
                ... Faces
                'FaceColor', [224 224 224]/256, ...
                'FaceAlpha', 0.8, ...
                ... Edges
                'EdgeColor','none', ...
                ... Callback Execution Control
                'PickableParts', 'none');
            obj.pa = patch(obj.Handle, ...
                ... Color
                'FaceColor', 'flat', ...
                'EdgeColor', 'none', ...
                'CData', [], ...
                'CDataMapping', 'direct', ...
                ... Data
                'XData', [], ...
                'YData', [], ...
                'ZData', [], ...
                ... Callback Execution Control
                'PickableParts', 'none');
            
            obj.index = obj.Parent.index;
        end
    end     % CONSTRUCTOR
end