classdef uisignallabels < TComponent
    properties (Constant)
        Type = 'panel'
    end
    properties (SetAccess = immutable)
        ax; tx
    end

    methods
        function updateuisign(obj)
            n = obj.Data.uisign.n;
            if n
                set(obj.ax, ...
                    'YLim', [0 n] + 0.5)
            else
                set(obj.ax, ...
                    'YLim', [0 1] + 0.5)
            end

            i = obj.Data.uisign.indices;
            if isempty(i)
                set(obj.tx(1), ...
                    'String', 'No Channels Selected', ...
                    'Color', 'k')
            else
                set(obj.tx(1:length(i)), ...
                    'FontSize', 8, ...
                    'FontWeight', 'bold', ...
                    'FontName', 'FixedWidth', ...
                    {'String'}, cellstr(string(num2cell(i)))', ...
                    'Color', 'k')
            end
        end
    end
    methods % CONSTRUCTOR
        function obj = uisignallabels()
            obj.ax = axes(obj.Handle, ...
                ... Ticks
                'XTick', [], ...
                'YTick', 1:256, ...
                ... Rulers
                'XLim', [0 1] + 0.5, ...
                'YLim', [0 1] + 0.5, ...
                'YDir', 'reverse', ...
                'XColor', 'none', ...
                'YColor', 'none', ...
                ... Grids
                'YGrid', 'on', ...
                'GridColor', [0.15 0.15 0.15], ...
                ... Colour
                'Color', 'w', ...
                ... Position
                'InnerPosition', [0 0 1 1]);
            hg = hggroup(obj.ax);
            obj.tx = text(hg, ...
                ones(256, 1), (1:256)', '', ...
                ... Text
                'Color', 'k', ...
                ... Font
                'FontSize', 10, ...
                'FontName', 'FixedWidth', ...
                'FontWeight', 'bold', ...
                ... Text Box
                'Rotation', 90, ...
                ... Position
                'HorizontalAlignment', 'center', ...
                ... Callbacks
                'PickableParts', 'none');
        end
    end     % CONSTRUCTOR
    methods (Access = protected)
        function initialise(obj)
            obj.Width = 20;
        end
    end     % INITIALISE
end