classdef uimaps_velocities_axes < TComponent
    properties (Constant)
        Type = "axes"
    end
    properties (SetAccess = immutable)
        index
    end
    properties (SetAccess = immutable)
        sf; qv; qv_peak; rc; ln
    end

    methods
        function updateuimaps(obj)
            obj.updateVelocityMap()
        end
        function updateuimaps_settings(obj)
            obj.updateVelocityMap()
        end
        function updateuimaps_positions(obj)
            switch obj.Data.cnfg.mode
                case 'flat'
                    set(obj.Handle, ...
                        'XLim', obj.Data.uimaps_positions.xlim, ...
                        'YLim', obj.Data.uimaps_positions.ylim)
                case 'sphere'
                    set(obj.Handle, ...
                        'XLim', [0 1], ...
                        'YLim', [0 1])
            end
        end
    end
    methods (Access = private)
        function updateVelocityMap(obj)
            if strcmp('flat', obj.Data.cnfg.mode) && ...
                    (obj.index <= obj.Data.uimaps.n)

                v = obj.Data.uimaps.vel(:, :, obj.index);
                b = obj.Data.uimaps.dir(:, :, obj.index);

                tf = (v > 0) & (v <= obj.Data.uimaps_settings.max_speed);
                tf_peak = (v > obj.Data.uimaps_settings.max_speed);

                
                set(obj.sf, ...
                    'XData', obj.Data.al_cont.xgrid, ...
                    'YData', obj.Data.al_cont.ygrid, ...
                    'ZData', zeros(size(v) + [1 1]), ...
                    'CData', padarray(v, [1 1], NaN, 'post'))

                f = 3;
                set(obj.qv, ...
                    'UData', sin(b(tf)) * f, ...
                    'VData', -cos(b(tf)) * f, ...
                    'XData', obj.Data.al_velo.xgrid(tf), ...
                    'YData', obj.Data.al_velo.ygrid(tf))
                set(obj.qv_peak, ...
                    'UData', sin(b(tf_peak)) * f, ...
                    'VData', -cos(b(tf_peak)) * f, ...
                    'XData', obj.Data.al_velo.xgrid(tf_peak), ...
                    'YData', obj.Data.al_velo.ygrid(tf_peak))
                set(obj.Handle, ...
                    'CLim', [0 obj.Data.uimaps_settings.max_speed])
            end
        end
    end
    methods (Access = protected)
        function traverseFcn(obj)
            p = obj.CurrentPosition;

            x = obj.Data.al_velo.xgrid;
            y = obj.Data.al_velo.ygrid;

            dx = x - p(1);
            dy = y - p(2);

            d = (dx.^2 + dy.^2);
            [~, i] = min(d, [], "all");
            
            v = obj.Data.uimaps.vel(:, :, obj.index);
            if isfinite(v(i))
                set(obj.ln, ...
                    "XData", x(i), ...
                    "YData", y(i))
                obj.Data.uimaps_highlight.setSpeed(v(i))
            else
                set(obj.ln, ...
                    "XData", [], ...
                    "YData", [])
                obj.Data.uimaps_highlight.setSpeed(NaN)
            end
        end
        function exitFcn(obj)
            set(obj.ln, ...
                "XData", [], ...
                "YData", [])
            obj.Data.uimaps_highlight.setSpeed(NaN)
        end
    end
    methods % CONSTRUCTOR
        function obj = uimaps_velocities_axes()
            set(obj.Handle, ...
                ... Rulers
                'XColor', [192 192 192]/256, ...
                'YColor', [192 192 192]/256, ...
                'YDir', 'reverse', ...
                ... Color and Transparency Maps
                'Colormap', cool, ...
                ... Box Styling
                'Color', 'w', ...
                'Box', 'on', ...
                ... Position
                'Units', 'normalized', ...
                'InnerPosition', [0.01 0.01 0.98 0.98], ...
                'DataAspectRatio', [1 1 1])

            obj.sf = surf([], ...
                'Parent', obj.Handle, ...
                ... Faces
                'FaceColor', 'flat', ...
                ... Edges
                'EdgeColor', 'none', ...
                ... Callback Execution Control
                'PickableParts', 'none');
            obj.ln = line(obj.Handle, ...
                ... Line
                'LineWidth', 1, ...
                ... Markers
                'Marker', 'o', ...
                'MarkerSize', 5, ...
                'MarkerFaceColor', 'w', ...
                'MarkerEdgeColor', [064 064 064]/256, ...
                ... Data
                'XData', double.empty(1,0), ...
                'YData', double.empty(1,0), ...
                ... Callback Execution Control
                'PickableParts', 'none');
            obj.qv = quiver(obj.Handle, [], [], ...
                ... Arrows
                'Color', [032 032 032]/256, ...
                'LineWidth', 1, ...
                'AutoScale', 'off', ...
                ... Marker
                'Marker', 'o', ...
                'MarkerSize', 2, ...
                'MarkerFaceColor', 'k', ...
                'MarkerEdgeColor', 'none', ...
                ... Callback Execution Control
                'PickableParts', 'none');
            obj.qv_peak = quiver(obj.Handle, [], [], ...
                ... Arrows
                'Color', [256 000 000]/256, ...
                'LineWidth', 1, ...
                'AutoScale', 'off', ...
                ... Marker
                'Marker', 'o', ...
                'MarkerSize', 2, ...
                'MarkerFaceColor', 'r', ...
                'MarkerEdgeColor', 'none', ...
                ... Callback Execution Control
                'PickableParts', 'none');

            obj.index = obj.Parent.index;
        end
    end     % CONSTRUCTOR
end